import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// Innovation scoring dimensions
const scoreDimensions = v.object({
  novelty: v.number(),
  feasibility: v.number(),
  impact: v.number(),
  scalability: v.number(),
  costEfficiency: v.number(),
  timeToMarket: v.number(),
});

// A single solution generated by one methodology
const solution = v.object({
  methodology: v.string(),
  title: v.string(),
  description: v.string(),
  keyInsights: v.array(v.string()),
  scores: v.optional(scoreDimensions),
});

// Source citation
const citation = v.object({
  title: v.string(),
  url: v.optional(v.string()),
  source: v.string(), // "web", "academic", "patent"
  snippet: v.optional(v.string()),
});

// Pipeline stage status
const stageStatus = v.union(
  v.literal("pending"),
  v.literal("running"),
  v.literal("completed"),
  v.literal("failed"),
);

export default defineSchema({
  challenges: defineTable({
    userId: v.string(),
    title: v.string(),
    description: v.string(),
    status: v.union(
      v.literal("pending"),
      v.literal("analyzing"),
      v.literal("completed"),
      v.literal("failed"),
    ),

    // Pipeline stage statuses
    stages: v.optional(
      v.object({
        decomposition: stageStatus,
        research: stageStatus,
        gapAnalysis: stageStatus,
        innovation: stageStatus,
        scoring: stageStatus,
        patent: stageStatus,
      }),
    ),

    // Stage 1: Problem Decomposition
    decomposition: v.optional(
      v.object({
        components: v.array(v.string()),
        constraints: v.array(v.string()),
        assumptions: v.array(v.string()),
        stakeholders: v.array(v.string()),
        successCriteria: v.array(v.string()),
      }),
    ),

    // Stage 2: Research results
    research: v.optional(
      v.object({
        existingSolutions: v.array(
          v.object({
            title: v.string(),
            description: v.string(),
            source: v.string(),
            url: v.optional(v.string()),
            strengths: v.array(v.string()),
            weaknesses: v.array(v.string()),
          }),
        ),
        citations: v.array(citation),
      }),
    ),

    // Stage 3: Gap Analysis
    gapAnalysis: v.optional(
      v.object({
        gaps: v.array(
          v.object({
            area: v.string(),
            description: v.string(),
            opportunity: v.string(),
          }),
        ),
        unmetNeeds: v.array(v.string()),
        underservedSegments: v.array(v.string()),
      }),
    ),

    // Stage 4: Innovation Generation (6 methodologies)
    solutions: v.optional(v.array(solution)),

    // Stage 5: Scoring (stored within each solution's scores field)

    // Stage 6: Patent Landscape
    patentLandscape: v.optional(
      v.object({
        existingPatents: v.array(
          v.object({
            title: v.string(),
            number: v.optional(v.string()),
            relevance: v.string(),
            summary: v.string(),
          }),
        ),
        whiteSpaces: v.array(v.string()),
        riskLevel: v.string(), // "low", "medium", "high"
        recommendation: v.string(),
      }),
    ),
  })
    .index("by_user", ["userId"])
    .index("by_status", ["status"]),
});
